env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:requirejs/recommended'
globals:
  requirejs: readonly
parserOptions:
  ecmaVersion: 6
plugins:
  - requirejs
rules:
  semi:
    - error
    - always